name: Auto-update code.version

on:
  push:
    paths:
      - 'lib_Code/code.h'
    branches:
      - main

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract commit hash
        id: get_hash
        run: echo "SHORT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Update code.version
        run: |
          echo "$SHORT_HASH" > lib_Code/code_installer/version/code.version
          echo "âœ… Updated version to $SHORT_HASH" > lib_Code/code_installer/version/code.version

      - name: Push new version
        run: |
          git config user.name "code-version-bot"
          git config user.email "code-version@users.noreply.github.com"
          git add lib_Code/version/code.version
          git commit -m "ðŸ”„ Auto-update code.version to $SHORT_HASH"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
